### ISSUE TITLE
Datadoc-json™ verification-function for external usage

### ISSUE THREAD

**Issue by aecorn** [statisticsnorway/datadoc#76]
Use-case:
I insert/map data programatically into the datadoc-jsons from existing sources (like MetaDB in DB1P), and before writing back to disk, I want to check that datadoc will except the json structure. If I check this before overwriting on disk, I hopefully, will avoid corrupted jsons or filling fields in unacceptable ways.

So something like
`datadoc.verify_external_json("path.json")`
If it could accept a local path, a json-string and a dict of dicts, that would be pretty cool.

**Comment by mmwinther** [comment]
@aecorn  This is already possible using Pydantic (which can directly read and verify json) and the models in `ssb-datadoc-model`. If you want a convenience function could you submit a PR for it?

A function like this should probably live in a separated directory in the repo (or a new repo), since it isn't part of the Datadoc app itself.

**Comment by aecorn** [comment]
So a "first home" could be a directory like "verification" in the repo `ssb-datadoc-model`.
If we want to "get at" the model, would it be smart to wrap that repo as a package anyway?
